# Generated by Django 5.0.6 on 2024-07-05 05:34

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(default=myapp.models.generate_unique_id, editable=False, max_length=6, unique=True),
        ),
    ]
